services:
  mysql:
    container_name: cine_db_container
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root_password # MySQL exige siempre una clave root
      MYSQL_DATABASE: cine_db
      MYSQL_USER: cine_user
      MYSQL_PASSWORD: cine_password
    ports:
      - "3307:3306" # Puerto estándar de MySQL
    volumes:
      - mysql_data:/var/lib/mysql # Ruta de datos de MySQL
    restart: always

volumes:
  mysql_data: